package br.com.slapp.genda.model;

/*
CREATE TABLE ACTIVIDADES(
	ACTIVIDAD	INT(10) AUTO_INCREMENT PRIMARY KEY,
	FECHA 		DATE,
	HORA 		INT(4),
	SERVICIO 	INT(10),
	PERIODOS 	INT(2),
	USUARIO 	INT(10),
	CLIENTE 	INT(10),
	PAGADO 		INT(1),
	NOTA 		VARCHAR(254) NOT NULL DEFAULT '',
	INACTIVO	INT(1) UNSIGNED NOT NULL DEFAULT '0'
) */
public class Atividade {

}
