package br.com.slapp.genda.model;

/*
CREATE TABLE CLIENTES(
	CLIENTE_ID 	INT(10) AUTO_INCREMENT PRIMARY KEY,
	CLIENTE_NM 	VARCHAR(50) NOT NULL,
	EMAIL 	   	VARCHAR(50) NOT NULL,
	CONTRASENA 	VARCHAR(50) NOT NULL,
	INACTIVO	INT(1) UNSIGNED NOT NULL DEFAULT '0'
)
*/
public class Cliente {

}
