package br.com.slapp.genda.model;
/*
CREATE TABLE PRESTADORES(
		PRESTADOR_ID 	INT(10) AUTO_INCREMENT PRIMARY KEY,
		PRESTADOR_NM 	VARCHAR(50) NOT NULL,
		EMPRESA 		INT(10),
		INACTIVO	   	INT(1) UNSIGNED NOT NULL DEFAULT '0'
	)
	insert into PRESTADORES(PRESTADOR_ID,PRESTADOR_NM,EMPRESA)
	     VALUES(1000,'DEPORTIVO BLAH CARMELITAS',1000),
	           (1001,'DEPORTIVO BLAH SAJONIA',1000),
	           (1002,'DEPORTIVO BLAH LUQUE',1000)
*/
public class Prestador {

}
