package br.com.slapp.genda.model;
/*
CREATE TABLE SERVICIOS (
		SERVICIO_ID 	INT(10) AUTO_INCREMENT PRIMARY KEY,
		SERVICIO_NM 	VARCHAR(50) NOT NULL,
		VALOR_UNIT 		DECIMAL(10,2),
		MINUTOS 		INT(4),
		PRESTADOR 		INT(10),
		NOTA 			VARCHAR(254) NOT NULL DEFAULT '',
		INACTIVO		INT(1) UNSIGNED NOT NULL DEFAULT '0'
	) 
	insert into SERVICIOS(SERVICIO_ID,SERVICIO_NM,VALOR_UNIT,MINUTOS,PRESTADOR)
	     VALUES(1001,'CANCHA 01 - BLAH CARMELITAS',100000,60,1000),
	           (1002,'CANCHA 02 - BLAH CARMELITAS',100000,60,1000)
*/
public class Servico {

}
